version: '3.7'

services:
    budget:
        image: budget/budget
        container_name: budget
        build:
            context: .
            dockerfile: ./.docker/Dockerfile
        ports:
          - 29078:80
        volumes:
          - .:/var/www
        networks:
            - localhost

networks:
    localhost:
        external: true
